### PR TITLE
Mobile single exhibitor

### PR DESCRIPTION
**Pull request by mikeyrayvon**

### CODE REVIEW

**Comment by varffs** [comment]
What is the intention with the pagination? Cus they dont equally split but I guess just fit to the box?

screen shot 2016-07-27 at 12 13 18

The overflowing of the arrow doesn't look great in that screenshot.

**Comment by varffs** [comment]
Also a more general thing. I think you should do more in style branches, or at least start with general components. I know sometimes there are dependencies but perhaps in those cases just do a bigger branch of core stuff. What I mean is that it is hard to review this PR as the typography and header/footer are still outstanding for mobile. So when looking at the output site rather than the code it is hard to see what is going on, what is just pending and what is missed, etc.

**Comment by mikeyrayvon** [comment]
ok i think the pagination arrows are ok

**Comment by varffs** [comment]
The merge into master effects the pagination arrows so they dont look like the branch did but I guess they are fine and will squash as desired now

**Pull request merged**
