### PR TITLE
Mobile exhibitors

### PR DESCRIPTION
**Pull request by mikeyrayvon**

### CODE REVIEW

**Comment by varffs** [comment]
@mikeyrayvon is this archive or single?

**Comment by varffs** [comment]
each exhibititor is `col-s-6` in the grid, should they be `col-s-12`?

screen shot 2016-08-04 at 18 14 01

**Comment by mikeyrayvon** [comment]
no, because there will be like 100 of them. and at least 2 in every letter

**Comment by varffs** [comment]
ah of course

**Pull request merged**
