### PR TITLE
Add metabox l10n

### PR DESCRIPTION
**Pull request by mikeyrayvon**

### CODE REVIEW

**Comment by varffs** [comment]
This doesnt work for me for site options and I can't really understand why. Working ok for normal post metaboxes.

Also I think we can just use the WP plugin installed as plugin rather than including. We already depend on q-translate-x and we are wanting to move to use CMB2 as a plugin as well soon.

**Comment by mikeyrayvon** [comment]
you have to reinit the qtranslate config. cause the new config file. open language settings and click save

**Comment by mikeyrayvon** [comment]
ok the plugin is called CMB2-qTranslate so add that to your install

**Comment by mikeyrayvon** [comment]
*Integration-CMB2-qTranslate

**Pull request merged**
